### ISSUE TITLE
Learn Flakes

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/journix#3]
### Tasks
- [x] Read sources:
    - [x] [NIX FLAKES, PART 1: AN INTRODUCTION AND TUTORIAL](https://www.tweag.io/blog/2020-05-25-flakes/)
    - [x] [Nix Flakes: first steps](https://blog.kubukoz.com/flakes-first-steps/)
    - [x] [Nix Flakes by Example, Part 1](https://www.breakds.org/post/flake-part-1-packaging/)
    - [x] [Learning Nix from the bottom up](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-9) - rejected: heavy bias towards rust users.
    - [x] [Nix flakes, and how to convert to them](https://garnix.io/blog/converting-to-flakes)
    - [x] [Nix By Example](https://ops.functionalalgebra.com/nix-by-example/) - rejected: outdated.
    - [x] [Nix Flakes: an Introduction](https://xeiaso.net/blog/nix-flakes-1-2022-02-21) - rejected: poorly written.
    - [x] [Flakes](https://nixos.wiki/wiki/Flakes) - rejected: parts are redundant or too specialised.
    - [x] [Nix Flakes in Production: What, Why and How](https://www.youtube.com/watch?v=o1Y7rWrPEO8)
    - [x] [TWEAG RFC0049 flakes.md](https://github.com/tweag/rfcs/blob/flakes/rfcs/0049-flakes.md)
    - [x] [Nix Based C++ Workflow From Scratch](https://www.breakds.org/post/nix-based-c++-workflow/)
    - [x] [NixOS & Flakes Book An unofficial book for beginners](https://nixos-and-flakes.thiscute.world/) - rejected: heavy bias towards NixOS users.
    - [x] [`nix flake` Reference](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-flake.html)
    - [x] [flake.nix Reference](https://github.com/NixOS/nix/blob/master/src/nix/flake.md)
    - [x] [numtide / flake-utils](https://github.com/numtide/flake-utils)
- [x] Record sources in repo wiki in sorted order or "Recommended Order" to learn flakes.
