### ISSUE TITLE
Learn Derivations

### ISSUE THREAD

**Issue by ianacaburian** [ianacaburian/journix#4]
### Tasks
- [x] Read sources:
    - [x] [How to Write a Nix Derivation](https://www.youtube.com/watch?v=bbW6kgB5F2M)
    - [x] [nix derivations](https://fasterthanli.me/series/building-a-rust-service-with-nix/part-9#nix-derivations)  
    - [x] [Our First Derivation](https://nixos.org/guides/nix-pills/our-first-derivation)
    - [x] [Working Derivation](https://nixos.org/guides/nix-pills/working-derivation)
    - [x] [Declarative App Builds and Environments: How to create Nix Derivations](https://lambdablob.com/posts/program-declarative-nix-package-derivations/)
